from io import BytesIO
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib import colors
from attendance.models import Attendance
from academics.models import Subject
from attendance.utils import calculate_attendance_percentage, get_cumulative_attendance

def generate_student_report(student):
    buffer = BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=letter)
    elements = []
    styles = getSampleStyleSheet()
    
    # Header
    elements.append(Paragraph(f"<b>{student.institution.name}</b>", styles['Title']))
    elements.append(Paragraph(f"Attendance Report: {student.get_full_name()}", styles['Heading2']))
    elements.append(Paragraph(f"Class: {student.class_ref.name if student.class_ref else 'N/A'}", styles['Normal']))
    elements.append(Paragraph(f"Email: {student.email}", styles['Normal']))
    elements.append(Spacer(1, 20))
    
    # Table Data
    data = [['Subject', 'Total Classes', 'Present', 'Absent', 'Percentage']]
    
    subjects = Subject.objects.filter(class_ref=student.class_ref)
    for subject in subjects:
        total = Attendance.objects.filter(student=student, subject=subject).count()
        present = Attendance.objects.filter(student=student, subject=subject, status='present').count()
        absent = total - present
        percent = calculate_attendance_percentage(student, subject)
        data.append([subject.name, str(total), str(present), str(absent), f"{percent}%"])
        
    t = Table(data)
    t.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,0), colors.HexColor('#4F46E5')),
        ('TEXTCOLOR', (0,0), (-1,0), colors.whitesmoke),
        ('ALIGN', (0,0), (-1,-1), 'CENTER'),
        ('FONTNAME', (0,0), (-1,0), 'Helvetica-Bold'),
        ('BOTTOMPADDING', (0,0), (-1,0), 12),
        ('BACKGROUND', (0,1), (-1,-1), colors.HexColor('#1E293B')),
        ('TEXTCOLOR', (0,1), (-1,-1), colors.whitesmoke),
        ('GRID', (0,0), (-1,-1), 1, colors.black),
    ]))
    
    elements.append(t)
    elements.append(Spacer(1, 20))
    
    # Cumulative
    cum_percent = get_cumulative_attendance(student)
    elements.append(Paragraph(f"<b>Cumulative Attendance: {cum_percent}%</b>", styles['Heading3']))
    
    if cum_percent < 75 and cum_percent > 0:
        elements.append(Paragraph("<font color='red'>Warning: Attendance is below 75% threshold!</font>", styles['Normal']))
        
    elements.append(Spacer(1, 50))
    elements.append(Paragraph("Generated by EduTrack System", styles['Normal']))
    
    doc.build(elements)
    buffer.seek(0)
    return buffer
